import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./../globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { SidebarProvider } from "@/components/ui/sidebar"
import { NavbarProvider } from "@/components/navbar-context"
import LayoutWrapper from "@/components/layout-wrapper"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          {/* Footer */}
          <footer className="bg-muted py-12 px-6">
            <div className="max-w-7xl mx-auto text-center">
              <h3 className="text-2xl font-bold mb-4 text-foreground">
                Professor Julian Gonzalez
              </h3>
              <p className="text-muted-foreground mb-6">Computer Science</p>
              <p className="text-muted-foreground max-w-2xl mx-auto leading-relaxed">
                Office Hours: Tuesday & Thursday 2:00-4:00 PM | Email:
                jane.smith@university.edu | Office: Science Building 342
              </p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
